export const steps = {
    CALENDAR: 'CALENDAR',
    TIMES: 'TIMES',
    BOOK_TYPE: 'BOOK_TYPE',
    PAYMENT: 'PAYMENT'
}

export const actions = {
    SET_STEP: 'SET_STEP',
    SET_SLOTS_INFO: 'SET_SLOTS_INFO',
    ADD_INPUT: 'ADD_INPUT',
    PAY_INIT: 'PAY_INIT',
    PAY_PROCESSING: 'PAY_PROCESSING',
    SAVE_BOOKING_INFO: 'SAVE_BOOKING_INFO'
}