export const actions = {
    SET_BOOKING_DATES: 'SET_BOOKING_DATES',
    SET_BOOKING_REQUESTS: 'SET_BOOKING_REQUESTS',
    DELETE_BOOKING_REQUEST: 'DELETE_BOOKING_REQUEST',

    SET_CREATED_EXPS: 'SET_CREATED_EXPS',
    SET_EDITING_EXP: 'SET_EDITING_EXP',
    CHANGE_EDIT_EXP: 'CHANGE_EDIT_EXP',
    CHANGE_EDIT_DATE: 'CHANGE_EDIT_DATE'
}