//User actions
export const userTypes = {
    SET_PROFILE: 'SET_PROFILE',
    SET_CREATOR_PROFILE: 'SET_CREATOR_PROFILE',
    ADD_NOTIFICATION: 'ADD_NOTIFICATION',
    DELETE_NOTIFICATION: 'DELETE_NOTIFICATION',
    SET_NUM_BOOKINGS: 'SET_NUM_BOOKINGS',
    RESET_USER: 'RESET_USER'
}

//Experience actions
export const experienceTypes = {
    SET_LOCATIONS: 'SET_LOCATIONS',
    SET_EXPS: 'SET_EXPS',
    SAVE_EXP: 'SAVE_EXP',
    UNSAVE_EXP: 'UNSAVE_EXP',
    SAVE_EXPERIENCE_FORM: 'SAVE_EXPERIENCE_FORM'
}

//User interface actions
export const uiTypes = {
    START_LOADING: 'START_LOADING',
    END_LOADING: 'END_LOADING',
    SHOW_ERROR: 'SHOW_ERROR',
    SHOW_SNACKBAR: 'SHOW_SNACKBAR',
    MESSAGE_SHOWN: 'MESSAGE_SHOWN',
    SET_LANGUAGE: 'SET_LANGUAGE'
}