//User actions
export const userTypes = {
    LOAD_PROFILE: 'LOAD_PROFILE',
    SET_USER_DATA: 'SET_USER_DATA',
    SET_CREATOR_DATA: 'SET_CREATOR_DATA',
    SET_USER_EXPS: 'SET_USER_PAST_EXPS',
    SAVE_EXP: 'SAVE_EXP',
    UNSAVE_EXP: 'UNSAVE_EXP',
    SET_MSG: 'SET_AUTH_MSG',
    RESET_USER: 'RESET_USER',
}